on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      - run: |
          pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m coverage run --source src/python -m unittest discover -s src/python; python -m coverage report --fail-under 100 --show-missing
